import { readFileSync, readdirSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { PAGESENSE_SRC } from "./analytics.ts";

/**
 * Run **after** `astro build`, which is why this file is not named `*.test.ts`
 * — the ordinary suite runs before the build and would read whatever `dist/`
 * happened to be lying around, which is a test that passes on a stale answer.
 *
 * `npm run check` runs it as its last step, and CI runs `npm run check`.
 *
 * What it is for: `kolonie-website#17` asks that a page added later cannot
 * silently miss the tag. Nothing in the source can promise that — only the
 * output can.
 */

const dist = fileURLToPath(new URL("../../dist", import.meta.url));

const pagesUnder = (directory: string): string[] =>
  readdirSync(directory).flatMap((entry) => {
    const path = join(directory, entry);
    if (statSync(path).isDirectory()) return pagesUnder(path);
    return entry.endsWith(".html") ? [path] : [];
  });

describe("the analytics tag in the built site", () => {
  const pages = pagesUnder(dist);

  it("built some pages at all", () => {
    // Astro emits an empty site without complaint if the content collection is
    // misconfigured, and an assertion over nothing passes.
    expect(pages.length).toBeGreaterThan(1);
  });

  it.each(pages.map((page) => page.slice(dist.length)))("is on %s", (page) => {
    expect(readFileSync(join(dist, page), "utf8")).toContain(PAGESENSE_SRC);
  });

  /**
   * The attribute is what keeps the page readable when the CDN hangs. A classic
   * `<script src>` in `<head>` stops the parser until it loads or fails; this
   * one does not, and losing the attribute would be a silent regression into a
   * blank page for as long as a connection takes to time out.
   */
  it.each(pages.map((page) => page.slice(dist.length)))("is deferred on %s", (page) => {
    const html = readFileSync(join(dist, page), "utf8");
    const tag = new RegExp(`<script[^>]*${PAGESENSE_SRC.replaceAll(".", "\\.")}[^>]*>`).exec(html);

    expect(tag?.[0]).toContain("defer");
  });

  /**
   * The one route here that must stay byte-clean. `/llms.txt` is generated by a
   * route and returns plain text; a script tag in it would be served to an agent
   * as content.
   */
  it("is not in /llms.txt", () => {
    const llms = readFileSync(join(dist, "llms.txt"), "utf8");

    expect(llms).not.toContain(PAGESENSE_SRC);
    expect(llms).not.toContain("<script");
  });
});
