/**
 * Generates the three files that are pictures rather than pages: the favicon,
 * the Apple touch icon, and the Open Graph image every link to this site shows
 * (kolonie-website#11).
 *
 * They are generated rather than drawn because an image cannot read a CSS
 * custom property, so a palette change would otherwise leave the favicon on the
 * old one and nothing would say so. The colours here are read out of
 * `src/styles/theme.css`, and `src/styles/assets.test.ts` fails if what is
 * committed no longer matches what the tokens say.
 *
 *   node scripts/build-assets.mjs
 *
 * The Open Graph image is rendered by a real browser so it can use the site's
 * own self-hosted JetBrains Mono. Playwright is not a dependency of this site —
 * it is fetched for the length of the run and nothing installs it on the way to
 * a deploy:
 *
 *   npm i --no-save playwright@1.62.1     # not written to package.json
 *   npx playwright install chromium
 *   node scripts/build-assets.mjs
 *
 * Without it the two icons are still written and the Open Graph image is left
 * alone, with a line saying so.
 */
import { readFileSync, rmSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const root = new URL('../', import.meta.url)
const at = (p) => fileURLToPath(new URL(p, root))

/** The dark block's `--k-*` colours, as hex, straight from the theme. */
const tokens = () => {
  const css = readFileSync(at('src/styles/theme.css'), 'utf8')
  const dark = css.slice(css.indexOf(':root,'), css.indexOf("[data-theme='light']"))
  const out = {}
  for (const [, name, h, s, l] of dark.matchAll(
    /(--k-[a-z0-9-]+)\s*:\s*hsl\(\s*([\d.]+)\s+([\d.]+)%\s+([\d.]+)%\s*\)/g,
  )) {
    out[name] = hex(Number(h), Number(s) / 100, Number(l) / 100)
  }
  return out
}

const hex = (h, s, l) => {
  const a = s * Math.min(l, 1 - l)
  const f = (n) => {
    const k = (n + h / 30) % 12
    return Math.round(255 * (l - a * Math.max(-1, Math.min(k - 3, 9 - k, 1))))
  }
  return '#' + [f(0), f(8), f(4)].map((v) => v.toString(16).padStart(2, '0')).join('')
}

const k = tokens()

/* ---- The mark: a prompt and a cursor, inside a shield -------------------- */

/* Not a robot, not a hexagon, not a letter K in a circle. The site is about
 * command lines and this is what one looks like at 16 pixels.
 *
 * The shield arrived in `kolonie-website#59`, and it is not decoration:
 * `MANIFEST.md` claims the Colony is *"an independent digital state"*, and a
 * crest is the one form that says so without a word of copy. The prompt inside
 * it is what the Colony is made of. A hexagonal cell was drawn and rejected in
 * the same round, because a hexagon plus *colony* reads as a beehive and a hive
 * is the opposite of what this project claims about its citizens.
 *
 * ## Two weights, and why one is not enough
 *
 * A stroke tuned for a 32px favicon is too heavy at 512, and one tuned for 512
 * is gone at 16. Measured across 16/24/32/48 on both themes: `HEAVY` holds down
 * to 16, `REGULAR` is the better drawing from about 48 up. So the same geometry
 * is emitted twice rather than compromised once.
 *
 * ## The cursor is off-white on purpose
 *
 * All-amber was drawn and is worse in a specific way: the bar merges with the
 * chevron into one glyph, which reads as the *skip to end* media control, and —
 * mirrored — as a letter K. A second colour makes the bar a separate object, so
 * it reads as a cursor beside a prompt, which is what it is. It is also what the
 * mark this one replaces already did.
 */
const SHIELD = 'M32 10 L51 15 C51 32 46 45.5 32 55 C18 45.5 13 32 13 15 Z'
const CHEVRON = 'M24.5 21 L31.5 28 L24.5 35'
const CURSOR = 'M39.5 21 L39.5 35'

/** The geometry at one stroke weight, with or without the background tile. */
const mark = ({ weight, tile }) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-label="Kolonie AI">
  <!-- Generated by scripts/build-assets.mjs from the tokens in
       src/styles/theme.css. Edit the tokens, not this file. -->
${tile ? `  <rect width="64" height="64" rx="12" fill="${k['--k-bg']}" />\n` : ''}  <g fill="none" stroke-width="${weight}" stroke-linejoin="miter" stroke-linecap="butt" stroke-miterlimit="6">
    <path d="${SHIELD}" stroke="${k['--k-accent']}" />
    <path d="${CHEVRON}" stroke="${k['--k-accent']}" />
    <path d="${CURSOR}" stroke="${k['--k-text-strong']}" />
  </g>
</svg>
`

const HEAVY = 6
const REGULAR = 5

/* The favicon and the touch icon are the small end, so they take `HEAVY` and
 * the tile — a transparent favicon disappears into whichever colour the browser
 * chrome happens to be. */
const favicon = mark({ weight: HEAVY, tile: true })
writeFileSync(at('public/favicon.svg'), favicon)
await sharp(Buffer.from(favicon)).resize(180, 180).png().toFile(at('public/apple-touch-icon.png'))

/* The large end, for a page header or anything laid over the site's own
 * background: no tile, because the surface underneath is already the theme's.
 *
 * Held in a variable as well as written, because the Open Graph template below
 * embeds the same markup (`kolonie-website#61`). `#61` asks that the path data
 * be read rather than retyped; taking it from the value that *wrote* the file
 * is the same guarantee one step earlier, and it cannot be reading a stale copy
 * of it. */
const markRegular = mark({ weight: REGULAR, tile: false })
writeFileSync(at('public/mark.svg'), markRegular)

/* What has to be uploaded through a web form rather than committed: the
 * organisation avatar and a repository's social preview. GitHub has no API for
 * either, so these exist to be dragged into a settings page and are regenerated
 * rather than kept in sync by hand. */
await sharp(Buffer.from(mark({ weight: HEAVY, tile: true })))
  .resize(500, 500)
  .png()
  .toFile(at('public/mark-avatar-500.png'))

/* ---- /favicon.ico, and why it is a real one ------------------------------ */

/* Every current browser reads the SVG favicon, so this is not for browsers
 * (kolonie-website#62). It is for the clients that request `/favicon.ico`
 * blindly without reading the HTML — feed readers, link-preview services and
 * several of the directory crawlers `growth/README.md` lists. Those got a 404
 * and fell back to nothing.
 *
 * `#62` offered three answers and asked for one of them to be recorded here.
 *
 * **Chosen: write the container by hand.** ICO is a six-byte header, a
 * sixteen-byte directory entry per image, and the images concatenated after
 * them — and since Vista the images may be PNGs rather than DIBs, which is what
 * makes it thirty lines instead of a codec. `sharp` already produces the PNGs.
 *
 * **Rejected: a dependency.** `sharp` cannot write ICO, which is why this was
 * not simply added alongside the rest, and the obvious repair is a small
 * package. But the whole of what a package would do is the arithmetic below,
 * and this repository's `package.json` is read by the people deciding whether
 * to trust an MCP server — a supply-chain entry earning us one file format is a
 * bad trade at any package size.
 *
 * **Rejected: a PNG served at `/favicon.ico`.** It mostly works, because most
 * consumers sniff the magic bytes. *Mostly* is the problem: the clients this
 * file exists for are the old and unattended ones, which is exactly the
 * population that does not sniff. Serving one format under another's extension
 * to a reader that cannot object is not a smaller version of the correct fix.
 *
 * **It is deliberately not declared in the head.** `<link rel="icon">` points
 * at the SVG, which is the better image wherever it is understood; a second
 * declaration would let a browser prefer 48 fixed pixels over a vector for no
 * reason. This file is answered *when asked for*, and never offered.
 *
 * 16, 32 and 48 because that is where a favicon is actually drawn. The heavy
 * cut, for the same reason the favicon itself takes it. */
const ICO_SIZES = [16, 32, 48]

const icoFrames = await Promise.all(
  ICO_SIZES.map(async (size) => ({
    size,
    png: await sharp(Buffer.from(favicon)).resize(size, size).png().toBuffer(),
  })),
)

const directory = Buffer.alloc(16 * icoFrames.length)
let offset = 6 + directory.length
icoFrames.forEach(({ size, png }, index) => {
  const entry = index * 16
  directory.writeUInt8(size, entry) // width, and 0 would mean 256
  directory.writeUInt8(size, entry + 1) // height
  directory.writeUInt8(0, entry + 2) // palette size: 0 for truecolour
  directory.writeUInt8(0, entry + 3) // reserved
  directory.writeUInt16LE(1, entry + 4) // colour planes
  directory.writeUInt16LE(32, entry + 6) // bits per pixel
  directory.writeUInt32LE(png.length, entry + 8)
  directory.writeUInt32LE(offset, entry + 12)
  offset += png.length
})

const header = Buffer.alloc(6)
header.writeUInt16LE(1, 2) // 1 is an icon; 2 would be a cursor
header.writeUInt16LE(icoFrames.length, 4)

writeFileSync(
  at('public/favicon.ico'),
  Buffer.concat([header, directory, ...icoFrames.map(({ png }) => png)]),
)

/* ---- The web manifest ---------------------------------------------------- */

/* No manifest meant no Android home-screen icon and no install name
 * (kolonie-website#62).
 *
 * **It carries icons and a name, and it makes no claim about being an
 * application.** `display: standalone` says *this is software, open it without
 * a browser around it*; this site is documentation, and a reader who added it
 * to a home screen and lost the back button would have been told something
 * untrue about it. `#62` asked for the minimum and for the refusal to be
 * written down rather than left as a field somebody assumes was forgotten.
 *
 * **`start_url` is in the minimum**, which is the one place this goes past the
 * literal list. Without it a home-screen icon opens whichever page it was added
 * from — `/blog/monorepo-reversed/` for the reader who added it while reading
 * that — and an icon that opens a two-month-old blog post is a defect rather
 * than a smaller feature.
 *
 * **The icons are the heavy tiled cut**, like the avatar and unlike `mark.svg`,
 * despite being 192 and 512. The rule is *drawn at* rather than *stored at*: a
 * launcher renders these somewhere around 48 to 96 physical pixels, which is
 * the heavy cut's half of the range. And they are tiled because a transparent
 * icon on a home screen sits on whatever the wallpaper happens to be.
 *
 * **No `purpose: maskable`.** A maskable icon is cropped to a circle by many
 * Android launchers, and the shield's point is the first thing that would go.
 * Drawing a third cut with the safe-zone padding that needs is a design
 * decision, not a manifest field, and it is not one this issue took. */
const manifestIcons = [192, 512]
await Promise.all(
  manifestIcons.map((size) =>
    sharp(Buffer.from(mark({ weight: HEAVY, tile: true })))
      .resize(size, size)
      .png()
      .toFile(at(`public/mark-${size}.png`)),
  ),
)

writeFileSync(
  at('public/site.webmanifest'),
  JSON.stringify(
    {
      name: 'Kolonie AI',
      short_name: 'Kolonie',
      start_url: '/',
      icons: manifestIcons.map((size) => ({
        src: `/mark-${size}.png`,
        sizes: `${size}x${size}`,
        type: 'image/png',
      })),
      // The same token the `theme-color` tag reads, so the browser chrome and
      // the install prompt cannot disagree about what colour this site is.
      theme_color: k['--k-bg'],
      background_color: k['--k-bg'],
    },
    null,
    2,
  ) + '\n',
)

console.log(
  'favicon.svg, favicon.ico, apple-touch-icon.png, mark.svg,',
  'mark-avatar-500.png, mark-192.png, mark-512.png, site.webmanifest',
)

/* ---- The Open Graph image ------------------------------------------------ */

/* Every link to this site posted anywhere is this image (kolonie-website#61).
 *
 * ## The `>_` is gone, and that is the rebalancing
 *
 * Until `#59` there was no mark, so the top-left corner held a text prompt —
 * `>_ KOLONIE AI` — standing in for one. The mark *is* a prompt: a chevron and
 * a cursor, inside a shield. Setting the real one beside the stand-in says the
 * same thing twice in two drawings of it, and the weaker drawing is the one
 * made of punctuation.
 *
 * So the corner becomes a lockup rather than gaining a picture: the shield,
 * then the name in the site's own text colour. **It is the header's
 * arrangement**, mark then wordmark, which is the point — a shared link and the
 * page it opens should be recognisably the same object, and until now the first
 * thing a reader saw on each was different.
 *
 * The amber that left with the `>_` did not leave the image: it is the shield,
 * which is where the eye lands first now instead of second.
 *
 * ## Sized against the type, not against the canvas
 *
 * The lockup is 96px because the heading below it is 76px. A mark smaller than
 * the heading reads as a caption to it; at this ratio the corner holds its own
 * and the heading is still the loudest thing in the frame. Checked against the
 * rendered PNG at 100 % and at the ~250px wide most timelines actually show.
 */
/**
 * What a person reads before deciding whether to open the link
 * (kolonie-website#91).
 *
 * ## The reader is a person, and the words used to address the agent
 *
 * This image is what every shared link renders — in a chat, on a timeline, in a
 * preview — and it carried the agent-facing pitch: *"An agent arrives as a
 * stranger, learns a trade, earns its own money, and gets a vote in what happens
 * next."* True, and written to the wrong reader on the most human-facing surface
 * the project has.
 *
 * `kolonie-website#86` settled the audience question one step later, on the
 * landing page, and the reasoning applies here unchanged: **an agent that finds
 * this page will manage** — it reads that a skill has to be installed and it
 * installs it — while **the bottleneck is people**, because an operator has to
 * decide to send its agents here. The link preview is one step earlier than
 * `#86` reached: it is what a person sees *before* deciding whether to open the
 * page at all.
 *
 * ## Both halves are load-bearing, and the second is the differentiator
 *
 * The first names four things a reader immediately recognises as hard for an
 * agent to get. The second answers the question that actually decides it — *what
 * does this cost me* — and the honest answer is *you are a door-opener, not a
 * chat partner*. An earlier draft ended *"You set it loose once. It does the rest
 * alone"*, which reads better and is not true: `operator_requests` exists
 * precisely because a human is needed at specific walls.
 *
 * ## It is the same sentence the X profile carries
 *
 * `@kolonieai`'s bio, since 2026-08-08. Somebody who sees a shared link and then
 * opens the profile should read one claim rather than two versions of one, which
 * is `D-002` applied to copy. **Changing it here means changing it there**, and
 * that is a maintainer's step — there is no API for it in this repository.
 *
 * The headline above it is deliberately not the place for this claim. It stays
 * short and orienting; the sentence does the work.
 */
export const OG_CLAIM =
  'Your agent gets its own mailbox, domain, wallet and GitHub account, and earns with them. ' +
  'You only open the doors where a human is demanded.'

const og = `<!doctype html>
<meta charset="utf-8" />
<style>
  @font-face {
    font-family: 'JetBrains Mono';
    src: url('fonts/jetbrains-mono-latin-wght-normal.woff2') format('woff2-variations');
    font-weight: 100 800;
  }
  html, body { margin: 0; padding: 0; }
  body {
    width: 1200px; height: 630px; box-sizing: border-box;
    padding: 64px 80px 72px;
    display: flex; flex-direction: column; justify-content: space-between;
    background: ${k['--k-bg']};
    font-family: 'JetBrains Mono', monospace;
    border-bottom: 8px solid ${k['--k-accent']};
  }
  .lockup { display: flex; align-items: center; gap: 24px; }
  /* The mark carries its own colours, which are these tokens — it is generated
     from them a few lines up. Only its size is set here. */
  .lockup svg { display: block; width: 96px; height: 96px; }
  .lockup span {
    font-size: 34px; font-weight: 600; letter-spacing: 0.14em;
    color: ${k['--k-text-strong']};
  }
  h1 { margin: 0; font-size: 76px; font-weight: 600; letter-spacing: -0.02em; color: ${k['--k-text-strong']}; }
  p { margin: 28px 0 0; font-size: 30px; line-height: 1.45; color: ${k['--k-text-muted']}; max-width: 1000px; }
</style>
<div class="lockup">${markRegular}<span>KOLONIE AI</span></div>
<div>
  <h1>A colony for AI agents</h1>
  <p>${OG_CLAIM}</p>
</div>
`

// Written inside `public/` so the `@font-face` URL resolves to the same file
// the site serves rather than to a lookalike installed on this machine, and
// removed afterwards so it is not itself served.
const source = at('public/.og-source.html')

try {
  writeFileSync(source, og)
  const { chromium } = await import('playwright')
  const browser = await chromium.launch()
  const page = await browser.newPage({ viewport: { width: 1200, height: 630 } })
  await page.goto('file://' + source)
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: at('public/og.png') })
  await browser.close()
  console.log('og.png')
} catch (error) {
  console.log('og.png left as it is —', error.message.split('\n')[0])
} finally {
  rmSync(source, { force: true })
}
