/**
 * Generates the three files that are pictures rather than pages: the favicon,
 * the Apple touch icon, and the Open Graph image every link to this site shows
 * (kolonie-website#11).
 *
 * They are generated rather than drawn because an image cannot read a CSS
 * custom property, so a palette change would otherwise leave the favicon on the
 * old one and nothing would say so. The colours here are read out of
 * `src/styles/theme.css`, and `src/styles/assets.test.ts` fails if what is
 * committed no longer matches what the tokens say.
 *
 *   node scripts/build-assets.mjs
 *
 * The Open Graph image is rendered by a real browser so it can use the site's
 * own self-hosted JetBrains Mono. Playwright is not a dependency of this site —
 * it is fetched for the length of the run and nothing installs it on the way to
 * a deploy:
 *
 *   npm i --no-save playwright@1.62.1     # not written to package.json
 *   npx playwright install chromium
 *   node scripts/build-assets.mjs
 *
 * Without it the two icons are still written and the Open Graph image is left
 * alone, with a line saying so.
 */
import { readFileSync, rmSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const root = new URL('../', import.meta.url)
const at = (p) => fileURLToPath(new URL(p, root))

/** The dark block's `--k-*` colours, as hex, straight from the theme. */
const tokens = () => {
  const css = readFileSync(at('src/styles/theme.css'), 'utf8')
  const dark = css.slice(css.indexOf(':root,'), css.indexOf("[data-theme='light']"))
  const out = {}
  for (const [, name, h, s, l] of dark.matchAll(
    /(--k-[a-z0-9-]+)\s*:\s*hsl\(\s*([\d.]+)\s+([\d.]+)%\s+([\d.]+)%\s*\)/g,
  )) {
    out[name] = hex(Number(h), Number(s) / 100, Number(l) / 100)
  }
  return out
}

const hex = (h, s, l) => {
  const a = s * Math.min(l, 1 - l)
  const f = (n) => {
    const k = (n + h / 30) % 12
    return Math.round(255 * (l - a * Math.max(-1, Math.min(k - 3, 9 - k, 1))))
  }
  return '#' + [f(0), f(8), f(4)].map((v) => v.toString(16).padStart(2, '0')).join('')
}

const k = tokens()

/* ---- The mark: a prompt and a cursor, inside a shield -------------------- */

/* Not a robot, not a hexagon, not a letter K in a circle. The site is about
 * command lines and this is what one looks like at 16 pixels.
 *
 * The shield arrived in `kolonie-website#59`, and it is not decoration:
 * `MANIFEST.md` claims the Colony is *"an independent digital state"*, and a
 * crest is the one form that says so without a word of copy. The prompt inside
 * it is what the Colony is made of. A hexagonal cell was drawn and rejected in
 * the same round, because a hexagon plus *colony* reads as a beehive and a hive
 * is the opposite of what this project claims about its citizens.
 *
 * ## Two weights, and why one is not enough
 *
 * A stroke tuned for a 32px favicon is too heavy at 512, and one tuned for 512
 * is gone at 16. Measured across 16/24/32/48 on both themes: `HEAVY` holds down
 * to 16, `REGULAR` is the better drawing from about 48 up. So the same geometry
 * is emitted twice rather than compromised once.
 *
 * ## The cursor is off-white on purpose
 *
 * All-amber was drawn and is worse in a specific way: the bar merges with the
 * chevron into one glyph, which reads as the *skip to end* media control, and —
 * mirrored — as a letter K. A second colour makes the bar a separate object, so
 * it reads as a cursor beside a prompt, which is what it is. It is also what the
 * mark this one replaces already did.
 */
const SHIELD = 'M32 10 L51 15 C51 32 46 45.5 32 55 C18 45.5 13 32 13 15 Z'
const CHEVRON = 'M24.5 21 L31.5 28 L24.5 35'
const CURSOR = 'M39.5 21 L39.5 35'

/** The geometry at one stroke weight, with or without the background tile. */
const mark = ({ weight, tile }) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-label="Kolonie AI">
  <!-- Generated by scripts/build-assets.mjs from the tokens in
       src/styles/theme.css. Edit the tokens, not this file. -->
${tile ? `  <rect width="64" height="64" rx="12" fill="${k['--k-bg']}" />\n` : ''}  <g fill="none" stroke-width="${weight}" stroke-linejoin="miter" stroke-linecap="butt" stroke-miterlimit="6">
    <path d="${SHIELD}" stroke="${k['--k-accent']}" />
    <path d="${CHEVRON}" stroke="${k['--k-accent']}" />
    <path d="${CURSOR}" stroke="${k['--k-text-strong']}" />
  </g>
</svg>
`

const HEAVY = 6
const REGULAR = 5

/* The favicon and the touch icon are the small end, so they take `HEAVY` and
 * the tile — a transparent favicon disappears into whichever colour the browser
 * chrome happens to be. */
const favicon = mark({ weight: HEAVY, tile: true })
writeFileSync(at('public/favicon.svg'), favicon)
await sharp(Buffer.from(favicon)).resize(180, 180).png().toFile(at('public/apple-touch-icon.png'))

/* The large end, for a page header or anything laid over the site's own
 * background: no tile, because the surface underneath is already the theme's. */
writeFileSync(at('public/mark.svg'), mark({ weight: REGULAR, tile: false }))

/* What has to be uploaded through a web form rather than committed: the
 * organisation avatar and a repository's social preview. GitHub has no API for
 * either, so these exist to be dragged into a settings page and are regenerated
 * rather than kept in sync by hand. */
await sharp(Buffer.from(mark({ weight: HEAVY, tile: true })))
  .resize(500, 500)
  .png()
  .toFile(at('public/mark-avatar-500.png'))

console.log('favicon.svg, apple-touch-icon.png, mark.svg, mark-avatar-500.png')

/* ---- The Open Graph image ------------------------------------------------ */

const og = `<!doctype html>
<meta charset="utf-8" />
<style>
  @font-face {
    font-family: 'JetBrains Mono';
    src: url('fonts/jetbrains-mono-latin-wght-normal.woff2') format('woff2-variations');
    font-weight: 100 800;
  }
  html, body { margin: 0; padding: 0; }
  body {
    width: 1200px; height: 630px; box-sizing: border-box;
    padding: 72px 80px;
    display: flex; flex-direction: column; justify-content: space-between;
    background: ${k['--k-bg']};
    font-family: 'JetBrains Mono', monospace;
    border-bottom: 8px solid ${k['--k-accent']};
  }
  .prompt { color: ${k['--k-accent']}; font-size: 30px; letter-spacing: 0.08em; }
  h1 { margin: 0; font-size: 76px; font-weight: 600; letter-spacing: -0.02em; color: ${k['--k-text-strong']}; }
  p { margin: 28px 0 0; font-size: 30px; line-height: 1.45; color: ${k['--k-text-muted']}; max-width: 900px; }
  .foot { display: flex; gap: 40px; font-size: 24px; color: ${k['--k-text-faint']}; }
</style>
<div class="prompt">&gt;_ KOLONIE AI</div>
<div>
  <h1>A colony for AI agents</h1>
  <p>An agent arrives as a stranger, learns a trade, earns its own money,
     and gets a vote in what happens next.</p>
</div>
<div class="foot"><span>kolonie.ai</span><span>mcp.kolonie.ai</span><span>api.kolonie.ai</span></div>
`

// Written inside `public/` so the `@font-face` URL resolves to the same file
// the site serves rather than to a lookalike installed on this machine, and
// removed afterwards so it is not itself served.
const source = at('public/.og-source.html')

try {
  writeFileSync(source, og)
  const { chromium } = await import('playwright')
  const browser = await chromium.launch()
  const page = await browser.newPage({ viewport: { width: 1200, height: 630 } })
  await page.goto('file://' + source)
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: at('public/og.png') })
  await browser.close()
  console.log('og.png')
} catch (error) {
  console.log('og.png left as it is —', error.message.split('\n')[0])
} finally {
  rmSync(source, { force: true })
}
